"""Core types and contracts (Phase 02).

Public, stable contract surface. Stability and deprecation policy:
``docs/core_contracts.md``. Downstream phases must depend on these contracts
only — never on concrete adapter implementations.
"""

from medfm.core.batch import BucketId, BucketKind, MedicalBatch
from medfm.core.encoder import (
    EncoderCapabilities,
    EncoderOutput,
    InputSpec,
    OutputSpec,
    PreprocessSpec,
    VisualEncoder,
)
from medfm.core.enums import (
    CURRENT_SCHEMA_VERSION,
    CoordinateSystem,
    LoadingMode,
    Modality,
    PrecisionMode,
    SplitName,
    StrictStrEnum,
    TaskType,
    register_enum_migration,
)
from medfm.core.errors import (
    BucketError,
    ContractError,
    IdentifierError,
    SchemaValidationError,
    SchemaVersionError,
    SerializationError,
    ShapeContractError,
    UnknownEnumValueError,
    UnsupportedCapabilityError,
    UnsupportedModalityError,
    UnsupportedTaskError,
)
from medfm.core.language import (
    GeneratedText,
    GenerationConfig,
    LanguageModelAdapter,
    LanguageModelCapabilities,
    LanguageOutput,
    ProjectedVisualTokens,
    TokenizedText,
)
from medfm.core.sample import (
    BoxTarget,
    ConversationTurn,
    ImageReference,
    LabelTarget,
    MedicalSample,
    PathologyMetadata,
    PatientIdHash,
    ProvenanceMetadata,
    SampleId,
    SegmentationTarget,
    SeriesIdHash,
    SpatialMetadata,
    StudyIdHash,
    patient_id_hash,
    series_id_hash,
    study_id_hash,
)
from medfm.core.serialization import (
    MAX_INLINE_TENSOR_ELEMENTS,
    TensorMeta,
    canonical_dtype_name,
    canonical_json,
    canonical_yaml,
    config_hash,
    dtype_from_canonical,
    materialize_cpu,
    tensor_from_data,
    tensor_to_data,
)
from medfm.core.task import LossOutput, TaskModule
from medfm.core.versioning import SCHEMA_VERSION, migrate_payload, register_schema_migration

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "MAX_INLINE_TENSOR_ELEMENTS",
    "SCHEMA_VERSION",
    "BoxTarget",
    "BucketError",
    "BucketId",
    "BucketKind",
    "ContractError",
    "ConversationTurn",
    "CoordinateSystem",
    "EncoderCapabilities",
    "EncoderOutput",
    "GeneratedText",
    "GenerationConfig",
    "IdentifierError",
    "ImageReference",
    "InputSpec",
    "LabelTarget",
    "LanguageModelAdapter",
    "LanguageModelCapabilities",
    "LanguageOutput",
    "LoadingMode",
    "LossOutput",
    "MedicalBatch",
    "MedicalSample",
    "Modality",
    "OutputSpec",
    "PathologyMetadata",
    "PatientIdHash",
    "PrecisionMode",
    "PreprocessSpec",
    "ProjectedVisualTokens",
    "ProvenanceMetadata",
    "SampleId",
    "SchemaValidationError",
    "SchemaVersionError",
    "SegmentationTarget",
    "SerializationError",
    "SeriesIdHash",
    "ShapeContractError",
    "SpatialMetadata",
    "SplitName",
    "StrictStrEnum",
    "StudyIdHash",
    "TaskModule",
    "TaskType",
    "TensorMeta",
    "TokenizedText",
    "UnknownEnumValueError",
    "UnsupportedCapabilityError",
    "UnsupportedModalityError",
    "UnsupportedTaskError",
    "VisualEncoder",
    "canonical_dtype_name",
    "canonical_json",
    "canonical_yaml",
    "config_hash",
    "dtype_from_canonical",
    "materialize_cpu",
    "migrate_payload",
    "patient_id_hash",
    "register_enum_migration",
    "register_schema_migration",
    "series_id_hash",
    "study_id_hash",
    "tensor_from_data",
    "tensor_to_data",
]
