"""Model registry and capabilities."""

from medfm.registry.acceptance import has_accepted, record_acceptance
from medfm.registry.core import ModelRegistry
from medfm.registry.plugins import (
    DummyPlugin,
    ModelPlugin,
    clear_plugins,
    get_plugin,
    register_plugin,
)
from medfm.registry.schema import (
    BACKEND_KEYS,
    REGISTRY_SCHEMA_VERSION,
    SUPPORTED_BACKEND_STATUSES,
    AttentionBackend,
    BackendStatus,
    BackendSupport,
    FeatureStatus,
    LicenseClass,
    LicenseSpec,
    LicenseStatus,
    MemoryEstimate,
    MemoryProfile,
    ModelCapability,
    ModelSpec,
    ModelStatus,
    OutputCapability,
    PeftCapability,
    Topology,
    WeightFormat,
)
from medfm.registry.smoke import (
    BackendUnavailableError,
    NoAdapterError,
    SmokeResult,
    run_smoke,
)
from medfm.registry.weights import (
    GatedAccessError,
    WeightIntegrityError,
    download_weights,
    inspect_weights,
    resolve_local_path,
    verify_file_hashes,
    verify_weight_integrity,
)

__all__ = [
    "ModelRegistry",
    "ModelSpec",
    "ModelCapability",
    "PeftCapability",
    "MemoryProfile",
    "MemoryEstimate",
    "LicenseSpec",
    "LicenseStatus",
    "LicenseClass",
    "FeatureStatus",
    "ModelStatus",
    "BackendStatus",
    "BackendSupport",
    "BACKEND_KEYS",
    "SUPPORTED_BACKEND_STATUSES",
    "REGISTRY_SCHEMA_VERSION",
    "WeightFormat",
    "Topology",
    "AttentionBackend",
    "OutputCapability",
    "download_weights",
    "verify_weight_integrity",
    "verify_file_hashes",
    "inspect_weights",
    "resolve_local_path",
    "GatedAccessError",
    "WeightIntegrityError",
    "has_accepted",
    "record_acceptance",
    "ModelPlugin",
    "DummyPlugin",
    "register_plugin",
    "get_plugin",
    "clear_plugins",
    "run_smoke",
    "SmokeResult",
    "NoAdapterError",
    "BackendUnavailableError",
]
