"""2D and native 3D visual-encoder adapters.

Adapters expose shared contract objects while keeping native segmentation,
prompt/memory, retrieval, and generation capabilities separate.
"""

from medfm.models.visual.base import (
    ADAPTER_CHECKPOINT_VERSION,
    AdapterCheckpointError,
    AdapterPreprocess,
    BackboneResult,
    BaseVisualAdapter2D,
    LinearHead,
    LoRAGateError,
    LoraTargetSpec,
    OptionalDependencyError,
)
from medfm.models.visual.ct_fm import (
    CTFM_MODEL_ID,
    CTFM_PREPROCESS,
    CTFM_REVISION,
    FLEXICT_MODEL_ID,
    FLEXICT_PREPROCESS,
    FLEXICT_REVISION,
    CTFMAdapter,
    FlexiCT3DAdapter,
    FlexiCTVLMAdapter,
)
from medfm.models.visual.hf_generic import FAMILIES, FamilySpec, GenericHFVisionAdapter
from medfm.models.visual.hoptimus0 import (
    HOPTIMUS_MODEL_ID,
    HOPTIMUS_PREPROCESS,
    HOPTIMUS_REVISION,
    HOptimus0Adapter,
    hoptimus_capabilities,
)
from medfm.models.visual.medgemma_vision import (
    MEDGEMMA_MODEL_ID,
    MEDGEMMA_PREPROCESS,
    MEDGEMMA_REVISION,
    MedGemmaVisionAdapter,
    medgemma_capabilities,
)
from medfm.models.visual.medsiglip import (
    MEDSIGLIP_MODEL_ID,
    MEDSIGLIP_PREPROCESS,
    MEDSIGLIP_REVISION,
    MedSigLIPAdapter,
    medsiglip_capabilities,
)
from medfm.models.visual.native_3d import (
    GenericMONAI3DAdapter,
    Native3DCheckpointError,
    Native3DOptionalDependencyError,
    Native3DPreprocess,
    sliding_window_inference,
)
from medfm.models.visual.native_tasks import (
    MEDSAM2_MODEL_ID,
    MEDSAM2_PREPROCESS,
    MEDSAM2_REVISION,
    NV_SEGMENT_MODEL_ID,
    NV_SEGMENT_PREPROCESS,
    NV_SEGMENT_REVISION,
    MedSAM2Adapter,
    NVSegmentCTMRAdapter,
)
from medfm.models.visual.raddino import (
    RADDINO_MODEL_ID,
    RADDINO_PREPROCESS,
    RADDINO_REVISION,
    RADDINOAdapter,
    raddino_capabilities,
)
from medfm.models.visual.research_3d import (
    M3D_CLIP_MODEL_ID,
    M3D_LAMED_MODEL_ID,
    M3D_REVISION,
    MERLIN_MODEL_ID,
    MERLIN_REVISION,
    M3DCLIPAdapter,
    M3DLaMedAdapter,
    MerlinAdapter,
)
from medfm.models.visual.triad import (
    TRIAD_MAE_MODEL_ID,
    TRIAD_MODEL_ID,
    TRIAD_PREPROCESS,
    TRIAD_REVISION,
    TRIAD_SIMMIM_MODEL_ID,
    TriadAdapter,
    TriadMAEAdapter,
    TriadSimMIMAdapter,
    triad_capabilities,
)

__all__ = [
    "ADAPTER_CHECKPOINT_VERSION",
    "AdapterCheckpointError",
    "AdapterPreprocess",
    "BackboneResult",
    "BaseVisualAdapter2D",
    "LinearHead",
    "LoRAGateError",
    "LoraTargetSpec",
    "OptionalDependencyError",
    "FAMILIES",
    "FamilySpec",
    "GenericHFVisionAdapter",
    "MedSigLIPAdapter",
    "MEDSIGLIP_MODEL_ID",
    "MEDSIGLIP_PREPROCESS",
    "MEDSIGLIP_REVISION",
    "medsiglip_capabilities",
    "RADDINOAdapter",
    "RADDINO_MODEL_ID",
    "RADDINO_PREPROCESS",
    "RADDINO_REVISION",
    "raddino_capabilities",
    "HOptimus0Adapter",
    "HOPTIMUS_MODEL_ID",
    "HOPTIMUS_PREPROCESS",
    "HOPTIMUS_REVISION",
    "hoptimus_capabilities",
    "MedGemmaVisionAdapter",
    "MEDGEMMA_MODEL_ID",
    "MEDGEMMA_PREPROCESS",
    "MEDGEMMA_REVISION",
    "medgemma_capabilities",
    "GenericMONAI3DAdapter",
    "Native3DPreprocess",
    "Native3DCheckpointError",
    "Native3DOptionalDependencyError",
    "sliding_window_inference",
    "CTFMAdapter",
    "CTFM_MODEL_ID",
    "CTFM_PREPROCESS",
    "CTFM_REVISION",
    "FlexiCT3DAdapter",
    "FlexiCTVLMAdapter",
    "FLEXICT_MODEL_ID",
    "FLEXICT_PREPROCESS",
    "FLEXICT_REVISION",
    "TriadAdapter",
    "TriadMAEAdapter",
    "TriadSimMIMAdapter",
    "TRIAD_MODEL_ID",
    "TRIAD_MAE_MODEL_ID",
    "TRIAD_SIMMIM_MODEL_ID",
    "TRIAD_PREPROCESS",
    "TRIAD_REVISION",
    "triad_capabilities",
    "NVSegmentCTMRAdapter",
    "NV_SEGMENT_MODEL_ID",
    "NV_SEGMENT_PREPROCESS",
    "NV_SEGMENT_REVISION",
    "MedSAM2Adapter",
    "MEDSAM2_MODEL_ID",
    "MEDSAM2_PREPROCESS",
    "MEDSAM2_REVISION",
    "MerlinAdapter",
    "MERLIN_MODEL_ID",
    "MERLIN_REVISION",
    "M3DCLIPAdapter",
    "M3DLaMedAdapter",
    "M3D_CLIP_MODEL_ID",
    "M3D_LAMED_MODEL_ID",
    "M3D_REVISION",
]
