"""Inference, deployment bundles, serving, and medical output contracts."""

from medfm.inference.audit import AUDIT_SCHEMA_VERSION, AuditEvent, AuditLogger, ClinicalAuditStore
from medfm.inference.bundle import (
    BUNDLE_LAYOUT,
    BUNDLE_SCHEMA_VERSION,
    BaseModelReference,
    BundleBuilder,
    BundleLoader,
    BundleManifest,
    DeploymentBundle,
    ModelBundle,
    RuntimeSupport,
    load_bundle,
    validate_bundle,
)
from medfm.inference.errors import (
    BackendInferenceError,
    BundleChecksumError,
    BundleCompatibilityError,
    BundleDependencyError,
    BundleError,
    BundleValidationError,
    InferenceError,
    InferenceTimeoutError,
    OptionalDependencyError,
    RequestLimitError,
    RequestValidationError,
    ServiceBusyError,
    StructuredOutputError,
    UnsupportedTaskError,
)
from medfm.inference.export_dicom import (
    DICOMExportPolicy,
    DICOMSourceReference,
    export_dicom_seg,
    hash_dicom_identifier,
    source_reference,
    validate_derived_geometry,
)
from medfm.inference.export_nifti import export_nifti, reopen_and_validate_nifti, restore_mask_to_original
from medfm.inference.generation import (
    GenerationConfig,
    GenerationResult,
    build_safe_prompt,
    generate,
    require_valid_output,
    select_length_bucket,
    validate_json_output,
)
from medfm.inference.pipeline import (
    BucketPolicy,
    ClassificationPipeline,
    InferencePipeline,
    InferenceRuntime,
    RetrievalPipeline,
    SegmentationPipeline,
    VLMPipeline,
    WSIPipeline,
)
from medfm.inference.schemas import (
    InferenceLimits,
    InferenceRequest,
    InferenceResponse,
    InferenceResult,
    InferenceTask,
    payload_hash,
    validate_request,
)
from medfm.inference.server import AdapterManager, AdapterRegistration, InferenceService
from medfm.inference.sliding_window import gaussian_importance_map, sliding_window_inference

__all__ = [
    "AUDIT_SCHEMA_VERSION",
    "BUNDLE_LAYOUT",
    "BUNDLE_SCHEMA_VERSION",
    "AdapterManager",
    "AdapterRegistration",
    "AuditEvent",
    "AuditLogger",
    "BackendInferenceError",
    "BaseModelReference",
    "BucketPolicy",
    "BundleBuilder",
    "BundleLoader",
    "DeploymentBundle",
    "BundleChecksumError",
    "BundleCompatibilityError",
    "BundleDependencyError",
    "BundleError",
    "BundleManifest",
    "BundleValidationError",
    "ClinicalAuditStore",
    "ClassificationPipeline",
    "DICOMExportPolicy",
    "DICOMSourceReference",
    "GenerationConfig",
    "GenerationResult",
    "InferenceError",
    "InferenceLimits",
    "InferencePipeline",
    "InferenceRequest",
    "InferenceResponse",
    "InferenceResult",
    "InferenceRuntime",
    "InferenceService",
    "InferenceTask",
    "InferenceTimeoutError",
    "ModelBundle",
    "OptionalDependencyError",
    "RequestLimitError",
    "RequestValidationError",
    "RetrievalPipeline",
    "RuntimeSupport",
    "SegmentationPipeline",
    "ServiceBusyError",
    "StructuredOutputError",
    "UnsupportedTaskError",
    "VLMPipeline",
    "WSIPipeline",
    "build_safe_prompt",
    "export_dicom_seg",
    "export_nifti",
    "gaussian_importance_map",
    "generate",
    "hash_dicom_identifier",
    "load_bundle",
    "payload_hash",
    "reopen_and_validate_nifti",
    "require_valid_output",
    "restore_mask_to_original",
    "select_length_bucket",
    "sliding_window_inference",
    "source_reference",
    "validate_bundle",
    "validate_derived_geometry",
    "validate_json_output",
    "validate_request",
]
