"""Backend-neutral task modules and losses for Phase 11."""

from .base import VISUAL_MODALITIES, TaskModuleBase, valid_sample_count, valid_sample_mask
from .classification import (
    BinaryClassificationTask,
    ClassificationTask,
    MultiLabelClassificationTask,
    OrdinalClassificationTask,
)
from .generation import StructuredGenerationTask
from .language_segmentation import LanguageConditionedSegmentationTask, LanguageQueryEncoder
from .localization import LocalizationTask
from .losses import (
    AsymmetricLoss,
    AsymmetricMultilabelLoss,
    BCEWithLogitsLoss,
    BinaryCrossEntropyWithLogitsLoss,
    BoundaryLoss,
    CrossEntropyClassificationLoss,
    CrossEntropyLoss,
    DeepSupervisionLoss,
    DiceBCELoss,
    DiceCELoss,
    DiceLoss,
    FocalClassificationLoss,
    FocalLoss,
    FocalSegmentationLoss,
    LabelSmoothingCrossEntropy,
    OrdinalCumulativeLinkLoss,
    OrdinalLoss,
    TverskyLoss,
    asymmetric_multilabel_loss,
    binary_cross_entropy_with_logits,
    cross_entropy,
    dice_bce_loss,
    dice_ce_loss,
    dice_loss,
    focal_loss,
    ordinal_loss,
)
from .multitask import (
    FixedWeight,
    LinearWeightSchedule,
    MultiTaskLoss,
    MultiTaskLossComposer,
    MultiTaskTask,
    TaskLossConfig,
    WeightingExtension,
    WeightSchedule,
)
from .reductions import reduce_loss_output, reduce_mean_by_count
from .retrieval import RetrievalTask
from .segmentation import BinarySegmentationTask, SegmentationTask
from .structured import (
    STRUCTURED_FINDINGS_SCHEMA,
    STRUCTURED_FINDINGS_SCHEMA_VERSION,
    StructuredFindingsError,
    StructuredFindingsValidator,
    StructuredGenerationResult,
    StructuredValidationReport,
    StructuredValidationResult,
    validate_generation_before_scoring,
    validate_structured_findings,
)

__all__ = [
    "TaskModuleBase",
    "VISUAL_MODALITIES",
    "valid_sample_count",
    "valid_sample_mask",
    "ClassificationTask",
    "BinaryClassificationTask",
    "MultiLabelClassificationTask",
    "OrdinalClassificationTask",
    "SegmentationTask",
    "BinarySegmentationTask",
    "LanguageConditionedSegmentationTask",
    "LanguageQueryEncoder",
    "RetrievalTask",
    "LocalizationTask",
    "StructuredGenerationTask",
    "MultiTaskLossComposer",
    "MultiTaskLoss",
    "MultiTaskTask",
    "TaskLossConfig",
    "FixedWeight",
    "LinearWeightSchedule",
    "WeightSchedule",
    "WeightingExtension",
    "BinaryCrossEntropyWithLogitsLoss",
    "BCEWithLogitsLoss",
    "CrossEntropyClassificationLoss",
    "CrossEntropyLoss",
    "FocalLoss",
    "FocalClassificationLoss",
    "LabelSmoothingCrossEntropy",
    "AsymmetricMultilabelLoss",
    "AsymmetricLoss",
    "OrdinalCumulativeLinkLoss",
    "OrdinalLoss",
    "DiceLoss",
    "dice_loss",
    "DiceCELoss",
    "DiceBCELoss",
    "FocalSegmentationLoss",
    "TverskyLoss",
    "BoundaryLoss",
    "DeepSupervisionLoss",
    "binary_cross_entropy_with_logits",
    "cross_entropy",
    "focal_loss",
    "asymmetric_multilabel_loss",
    "ordinal_loss",
    "dice_ce_loss",
    "dice_bce_loss",
    "STRUCTURED_FINDINGS_SCHEMA_VERSION",
    "STRUCTURED_FINDINGS_SCHEMA",
    "StructuredFindingsError",
    "StructuredFindingsValidator",
    "StructuredValidationResult",
    "StructuredValidationReport",
    "StructuredGenerationResult",
    "validate_structured_findings",
    "validate_generation_before_scoring",
    "reduce_mean_by_count",
    "reduce_loss_output",
]
