"""Cross-attention language-conditioned segmentation decoder."""

from __future__ import annotations

from collections.abc import Sequence

import torch
from torch import nn

from medfm.core.errors import ShapeContractError

from .base import SegmentationOutput, as_feature_maps


class LanguageConditionedMaskDecoder(nn.Module):
    """Fuse text embeddings with dense visual features before mask generation.

    Text is used only as a conditioning signal.  The returned logits are
    generated by a spatial ``1x1``/``1x1x1`` head over visual feature maps;
    text tokens are never reshaped into a mask.
    """

    def __init__(
        self,
        visual_dim: int,
        text_dim: int,
        *,
        hidden_dim: int | None = None,
        out_channels: int = 1,
        num_heads: int = 4,
    ) -> None:
        super().__init__()
        if visual_dim <= 0 or text_dim <= 0 or out_channels <= 0:
            raise ShapeContractError("language-conditioned decoder dimensions must be positive")
        hidden = int(hidden_dim or max(8, min(visual_dim, text_dim)))
        if hidden <= 0 or hidden % max(1, min(num_heads, hidden)) != 0:
            # The implementation uses explicit scaled dot-product attention,
            # so num_heads is retained as metadata rather than imposing a
            # MultiheadAttention divisibility constraint.
            hidden = max(1, hidden)
        self.visual_dim = int(visual_dim)
        self.text_dim = int(text_dim)
        self.hidden_dim = hidden
        self.out_channels = int(out_channels)
        self.num_heads = int(num_heads)
        self.visual_projection = nn.Linear(visual_dim, hidden)
        self.text_key = nn.Linear(text_dim, hidden)
        self.text_value = nn.Linear(text_dim, hidden)
        self.fusion = nn.Sequential(nn.Linear(hidden * 2, hidden), nn.GELU(), nn.Linear(hidden, hidden))
        self._heads = nn.ModuleDict()
        # Heads are created lazily per spatial rank so one module supports both
        # 2D and 3D feature maps behind the same interface.
        self.head_2d = nn.Conv2d(hidden, out_channels, kernel_size=1)
        self.head_3d = nn.Conv3d(hidden, out_channels, kernel_size=1)

    @staticmethod
    def _safe_text_pool(text: torch.Tensor, text_mask: torch.Tensor | None) -> tuple[torch.Tensor, torch.Tensor]:
        if text.ndim == 2:
            text = text.unsqueeze(1)
        if text.ndim != 3:
            raise ShapeContractError("text embeddings must be [B, L, D] or [B, D]")
        if text_mask is None:
            text_mask = torch.ones(text.shape[:2], dtype=torch.bool, device=text.device)
        else:
            if tuple(text_mask.shape) != tuple(text.shape[:2]):
                raise ShapeContractError("text_mask must have shape [B, L]")
            text_mask = text_mask.to(device=text.device, dtype=torch.bool)
        weights = text_mask.to(dtype=text.dtype).unsqueeze(-1)
        pooled = (text * weights).sum(dim=1) / weights.sum(dim=1).clamp_min(1.0)
        valid = text_mask.any(dim=1)
        return pooled, valid

    def forward(
        self,
        visual_features: torch.Tensor | Sequence[torch.Tensor],
        text_embeddings: torch.Tensor,
        *,
        text_mask: torch.Tensor | None = None,
        query_mask: torch.Tensor | None = None,
        output_size: Sequence[int] | None = None,
    ) -> SegmentationOutput:
        maps = as_feature_maps(visual_features)
        visual = maps[-1]
        if int(visual.shape[1]) != self.visual_dim:
            raise ShapeContractError(f"visual feature channels {visual.shape[1]} != configured {self.visual_dim}")
        text_pooled, valid_text = self._safe_text_pool(text_embeddings, text_mask)
        if query_mask is not None:
            if query_mask.ndim != 1 or tuple(query_mask.shape) != (visual.shape[0],):
                raise ShapeContractError("query_mask must be [B] for one language query per sample")
            valid_text = valid_text & query_mask.to(device=valid_text.device, dtype=torch.bool)
        visual_tokens = visual.flatten(2).transpose(1, 2)
        visual_q = self.visual_projection(visual_tokens)
        text_k = self.text_key(text_pooled).unsqueeze(1)
        text_v = self.text_value(text_pooled).unsqueeze(1)
        scores = torch.einsum("bsd,bld->bsl", visual_q, text_k) / self.hidden_dim**0.5
        # There is one pooled text key. Multiplication by valid_text avoids
        # NaNs from an all-masked query while making missing-class output zero.
        attention = torch.sigmoid(scores) * valid_text.reshape(-1, 1, 1).to(dtype=scores.dtype)
        fused = self.fusion(torch.cat([visual_q, attention * text_v], dim=-1))
        fused = fused.transpose(1, 2).reshape(visual.shape[0], self.hidden_dim, *visual.shape[2:])
        head = self.head_2d if visual.ndim == 4 else self.head_3d
        logits = head(fused)
        if output_size is not None and tuple(int(v) for v in output_size) != tuple(logits.shape[2:]):
            mode = "bilinear" if logits.ndim == 4 else "trilinear"
            logits = torch.nn.functional.interpolate(
                logits, size=tuple(int(v) for v in output_size), mode=mode, align_corners=False
            )
        logits = logits * valid_text.reshape(-1, 1, *([1] * (logits.ndim - 2))).to(dtype=logits.dtype)
        return SegmentationOutput(
            logits=logits,
            auxiliary={"decoder": "language_conditioned", "query_valid": valid_text},
        )


__all__ = ["LanguageConditionedMaskDecoder"]
